package com.scarlett.bean.dao;

import java.io.Serializable;
import java.util.Date;

public class BestCaseDao implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column best_case.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column best_case.student_name
     *
     * @mbg.generated
     */
    private String studentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column best_case.photo_url
     *
     * @mbg.generated
     */
    private String photoUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column best_case.mini_title
     *
     * @mbg.generated
     */
    private String miniTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column best_case.describe_url
     *
     * @mbg.generated
     */
    private String describeUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column best_case.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column best_case.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table best_case
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column best_case.id
     *
     * @return the value of best_case.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column best_case.id
     *
     * @param id the value for best_case.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column best_case.student_name
     *
     * @return the value of best_case.student_name
     *
     * @mbg.generated
     */
    public String getStudentName() {
        return studentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column best_case.student_name
     *
     * @param studentName the value for best_case.student_name
     *
     * @mbg.generated
     */
    public void setStudentName(String studentName) {
        this.studentName = studentName == null ? null : studentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column best_case.photo_url
     *
     * @return the value of best_case.photo_url
     *
     * @mbg.generated
     */
    public String getPhotoUrl() {
        return photoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column best_case.photo_url
     *
     * @param photoUrl the value for best_case.photo_url
     *
     * @mbg.generated
     */
    public void setPhotoUrl(String photoUrl) {
        this.photoUrl = photoUrl == null ? null : photoUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column best_case.mini_title
     *
     * @return the value of best_case.mini_title
     *
     * @mbg.generated
     */
    public String getMiniTitle() {
        return miniTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column best_case.mini_title
     *
     * @param miniTitle the value for best_case.mini_title
     *
     * @mbg.generated
     */
    public void setMiniTitle(String miniTitle) {
        this.miniTitle = miniTitle == null ? null : miniTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column best_case.describe_url
     *
     * @return the value of best_case.describe_url
     *
     * @mbg.generated
     */
    public String getDescribeUrl() {
        return describeUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column best_case.describe_url
     *
     * @param describeUrl the value for best_case.describe_url
     *
     * @mbg.generated
     */
    public void setDescribeUrl(String describeUrl) {
        this.describeUrl = describeUrl == null ? null : describeUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column best_case.update_time
     *
     * @return the value of best_case.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column best_case.update_time
     *
     * @param updateTime the value for best_case.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column best_case.create_time
     *
     * @return the value of best_case.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column best_case.create_time
     *
     * @param createTime the value for best_case.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}