package com.scarlett.bean.dao;

import java.io.Serializable;
import java.util.Date;

public class VisitHistoryDao implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit_history.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit_history.view_name
     *
     * @mbg.generated
     */
    private String viewName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit_history.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit_history.remote_ip
     *
     * @mbg.generated
     */
    private String remoteIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit_history.popu_channel
     *
     * @mbg.generated
     */
    private String popuChannel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit_history.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit_history.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table visit_history
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit_history.id
     *
     * @return the value of visit_history.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit_history.id
     *
     * @param id the value for visit_history.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit_history.view_name
     *
     * @return the value of visit_history.view_name
     *
     * @mbg.generated
     */
    public String getViewName() {
        return viewName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit_history.view_name
     *
     * @param viewName the value for visit_history.view_name
     *
     * @mbg.generated
     */
    public void setViewName(String viewName) {
        this.viewName = viewName == null ? null : viewName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit_history.user_id
     *
     * @return the value of visit_history.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit_history.user_id
     *
     * @param userId the value for visit_history.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit_history.remote_ip
     *
     * @return the value of visit_history.remote_ip
     *
     * @mbg.generated
     */
    public String getRemoteIp() {
        return remoteIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit_history.remote_ip
     *
     * @param remoteIp the value for visit_history.remote_ip
     *
     * @mbg.generated
     */
    public void setRemoteIp(String remoteIp) {
        this.remoteIp = remoteIp == null ? null : remoteIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit_history.popu_channel
     *
     * @return the value of visit_history.popu_channel
     *
     * @mbg.generated
     */
    public String getPopuChannel() {
        return popuChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit_history.popu_channel
     *
     * @param popuChannel the value for visit_history.popu_channel
     *
     * @mbg.generated
     */
    public void setPopuChannel(String popuChannel) {
        this.popuChannel = popuChannel == null ? null : popuChannel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit_history.update_time
     *
     * @return the value of visit_history.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit_history.update_time
     *
     * @param updateTime the value for visit_history.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit_history.create_time
     *
     * @return the value of visit_history.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit_history.create_time
     *
     * @param createTime the value for visit_history.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}