package com.scarlett.dal.mapper;

import java.util.List;

import com.scarlett.bean.dao.BestCaseDao;
import com.scarlett.bean.dao.BestCaseDaoCriteria;
import org.apache.ibatis.annotations.Param;

public interface BestCaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table best_case
     *
     * @mbg.generated
     */
    long countByExample(BestCaseDaoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table best_case
     *
     * @mbg.generated
     */
    int deleteByExample(BestCaseDaoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table best_case
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table best_case
     *
     * @mbg.generated
     */
    int insert(BestCaseDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table best_case
     *
     * @mbg.generated
     */
    int insertSelective(BestCaseDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table best_case
     *
     * @mbg.generated
     */
    List<BestCaseDao> selectByExample(BestCaseDaoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table best_case
     *
     * @mbg.generated
     */
    BestCaseDao selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table best_case
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") BestCaseDao record, @Param("example") BestCaseDaoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table best_case
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") BestCaseDao record, @Param("example") BestCaseDaoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table best_case
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BestCaseDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table best_case
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BestCaseDao record);
}