package com.scarlett.dal.mapper;

import com.scarlett.bean.dao.VisitHistoryDao;
import com.scarlett.bean.dao.VisitHistoryDaoCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VisitHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visit_history
     *
     * @mbg.generated
     */
    long countByExample(VisitHistoryDaoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visit_history
     *
     * @mbg.generated
     */
    int deleteByExample(VisitHistoryDaoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visit_history
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visit_history
     *
     * @mbg.generated
     */
    int insert(VisitHistoryDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visit_history
     *
     * @mbg.generated
     */
    int insertSelective(VisitHistoryDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visit_history
     *
     * @mbg.generated
     */
    List<VisitHistoryDao> selectByExample(VisitHistoryDaoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visit_history
     *
     * @mbg.generated
     */
    VisitHistoryDao selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visit_history
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") VisitHistoryDao record, @Param("example") VisitHistoryDaoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visit_history
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") VisitHistoryDao record, @Param("example") VisitHistoryDaoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visit_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(VisitHistoryDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visit_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(VisitHistoryDao record);
}